name: teste_mundo_wap
description: "A Mundo Wap test project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0+1001

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  provider: ^6.1.5
  flutter_dotenv: ^5.2.1
  loading_animation_widget: ^1.3.0
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  sqfentity: ^2.5.0
  sqfentity_gen: ^2.5.0
  connectivity_plus: ^6.1.4
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  geolocator: ^14.0.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  build_verify: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
